[package]
name = "rust-euler"
version = "0.1.1"
authors = ["Kaan Karaoglu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rustfmt = "0.10.0"
